name: Run tests

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    # Make DATABASE_URL available to imports that read it at import-time.
    env:
      DATABASE_URL: postgresql://postgres:postgres@localhost:5432/gradcafe
      FLASK_ENV: testing
      PYTHONDONTWRITEBYTECODE: "1"
      PIP_DISABLE_PIP_VERSION_CHECK: "1"

    services:
      postgres:
        image: postgres:13
        ports:
          - 5432:5432
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: gradcafe
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        working-directory: module_4
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run tests (marked suites)
        working-directory: module_4
        run: pytest -m "web or buttons or analysis or db or integration" --maxfail=1 -vv
